import React from "react";
import Head from "next/head";
import styles from "../styles/Home.module.scss";
import PostsList from "../components/PostsList/PostsList";

function Favorites({ posts }) {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Noon IG Clone | Favorites</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.jpeg" />
      </Head>
      <header>
        
      </header>
      <PostsList posts={posts} isFavorites={true} />
    </div>
  );
}



export default Favorites;